### ISSUE TITLE
compile error on macOS

### ISSUE THREAD

**Issue by grylem** [whatdoineed2do/audiotag#2]
Try compile on macOS but
audiotag.cc:414:42: error: no member named 'st_mtim' in 'stat'
                tv[1].tv_sec  = ff->st().st_mtim.tv_sec;
                                ~~~~~~~~ ^
audiotag.cc:415:42: error: no member named 'st_mtim' in 'stat'
                tv[1].tv_usec = ff->st().st_mtim.tv_nsec/1000;

**Comment by whatdoineed2do** [comment]
I don't have access to a Mac but this appears to be quite a common problem - if you delete those two lines (414 and 415) then this will compile - it'll simply never try to keep the dates of your files unmodified

**Comment by grylem** [comment]
Thank. Now i have 11 warning but can compile

**Comment by whatdoineed2do** [comment]
v1.2.4.1 cleans this up
